hello: I'm dev.
test:
  port: 8002
  application: config-eureka-client
server:
  port: 8002

spring:
  application:
    # 应用名称
    name: config-eureka-client
# 自定义配置
name: system-dev
# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/